# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/akira/go-puppetdb";
    fetch = {
      type = "git";
      url = "https://github.com/akira/go-puppetdb";
      rev = "172cf689a99c50d831e4a8c2cc5dfa06fe92aea0";
      sha256 = "12nk4q8mcvj80fs2famlg4bpzb6w9sy57kp1bn0420m171n6hccc";
    };
  }
  {
    goPackagePath = "github.com/miekg/dns";
    fetch = {
      type = "git";
      url = "https://github.com/miekg/dns";
      rev = "271c58e0c14f552178ea321a545ff9af38930f39";
      sha256 = "1ns2ccahl3msid86935hm8baia89fj0fpgpqwrhmr58gq064hb6q";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "a5b47d31c556af34a302ce5d659e6fea44d90de0";
      sha256 = "0v6l48fshdjrqzyq1kwn22gy7vy434xdr1i0lm3prsf6jbln9fam";
    };
  }
]
