# DEVBOX
ifndef::env-github[]
include::meta.adoc[]
:env-devbox:
{latest_revision}
endif::env-github[]
:page-layout: docs
:toc: left
:toclevels: 2
:numbered:
:sectnumlevels: 1
:nofooter:
:icons: font
:docinfo1:
:source-language: bash
:source-highlighter: pygments
:experimental:
ifdef::env-github[]
:toc-placement: preamble
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::env-github[]


toc::[]

## Software requirements

- Virtualbox 5.1.x
- Vagrant 1.8.x


## Quick first time setup

### ssh keys

In the host, pick a folder of your choice (where the `Vagrantfile` will sit). In this folder:

1. create a directory `ssh-keys`.
2. in the ssh-keys subfolder, copy your `Bitbucket` key pair, rename them 'cirb_rsa' and 'cirb_rsa.pub' respectively if the filename differs.
3. in the ssh-keys subfolder, copy your `Github` key pair, rename them 'cirb_github_rsa' and 'cirb_github_rsa.pub'. If you use the same key pair, copy the previous pair and rename accordingly.
4. optionally copy the https://github.com/CIRB/devbox/blob/master/user/params.sh[params file]. Do not copy/paste from Github UI, download source and edit to avoid unwanted characters.

### box import

Open a terminal in the picked folder and type:

To download the base box from our CIRB repository:
```
vagrant box add devbox http://repo.irisnet.be/boxes/devbox.box <1>
```
<1> You can also use 'devbox-novagrant.box' and maintain a Vagrantfile locally

To initialize the box:
```
vagrant init devbox && vagrant up
```
NOTE: if you are using an older version of virtualbox (5.0.2x), you will have to *connect the cable*. See <<Troubleshooting>>

To finalize your first time setup, restart your box:
```
vagrant reload
```


## Usage

### vagrant

```
# shutdown the vm
vagrant halt
# boot the vm
vagrant up
# update configuration
vagrant provision
# destroy the box (all local state is lost)
vagrant destroy
```

The provisioning is done automatically the first time `vagrant up` is executed. You can provision again later on by using `vagrant provision`. This is useful to check for a configuration update.

Provisioning is separated into two steps: `system` to configure the system and `user` to configure the vagrant user. You can selectively ask for provisioning using:

```
vagrant provision --provision-with system
vagrant provision --provision-with user
```

### operating system

The devbox is based on https://nixos.org/[NixOS] version 16.09. NixOS is a Linux distribution based on the https://nixos.org/nix/[nix] package manager.

The whole system setup is declared in https://github.com/CIRB/devbox/blob/master/system/configuration.nix.

To clean-up the store (whenever the disk usage is too high) use:

```
→ sudo nix-collect-garbage -d
```

### windows manager

The devbox comes with a https://en.wikipedia.org/wiki/Tiling_window_manager[tiling windows manager] called http://xmonad.org/[xmonad]. Such a minimal approach has been chosen for 3 reasons:

* Efficiency: the box needs to consume as minimum CPU/Mem resources as possible
* Simplicity: the window manager is basic but yet quite flexible
* Practicality: the desktop is distraction free.

#### minimal cheat sheet

|======
|Command |Description

| kbd:[<Super> p] |Open Menu
| kbd:[<Super> t] |New terminal
| kbd:[<Super> 1..9] |Go to nth desktop
| kbd:[<Super> <Shift> 1..9] |Switch to nth desktop
| kbd:[<Super> Space] |Change between horizontal, vertical and stack layout
| kbd:[<Super> Tab] |In stack layout, switch the stacked window
| kbd:[<Super> <Shift> c] |Close (kill) current window
| kbd:[<Super> m] kbd:[<Super> h] |Resize windows
| kbd:[F 1] |Open this README in a browser
|======

### terminal emulator

The `devbox` uses the `urxvt` terminal for its speed and customization.

|=====
|Command | Description

|kbd:[<Control> <Meta> p]|Change theme
|kbd:[<Control> <Shift> up/down] |Increase/Decrease font size
|kbd:[<Meta> <s>] |Search console output
|kbd:[<Control><Meta> c/v] | Copy/paste to/from clipboard
|=====

The default shell is `zsh` which allows for predictable history and completion.
You can revert to using `bash` as your default shell if you wish by removing all zsh related lines in the `/etc/nixos/local-configuration.nix` file.

You might want to enable some `oh-my-zsh` plugins by updating your zshrc. None has been enabled by default to avoid unwanted intrusion. See https://github.com/PierreR/dotfiles/blob/a8e45029767a22998f7a68fdf114297255495d0e/.zshrc#L3[here] for one example.


### projects

By default, there will be no project on the box. You will need to enable some `mr` repositories associated with your `hostgroup`.

For instance, for the `bos` hostgroup, you would do the following:

```
→ cd .config/mr/config.d
→ ln -s ../available.d/puppet-bos.mr .
→ ln -s ../available.d/salt-bos.mr .
→ cd
→ mr -f up <1>
```
<1> you usually don't want to automatically update such repository on provisioning. That's the reason behind the `-f` (force) flag.

By convention, all `cicd` projects will be placed inside the `/projects/cicd` folder hierarchy.

### cicd

You can use a semantic name as a `dns` to lookup any machine known by `puppetdb`. The pattern to use is: #$subgroup.$role.$hostgroup.zone.cicd#.

For instance if you want to connect through ssh to the `bos` jenkins slave, you can (inside the devbox) use:

```
→  ssh -i ~/.cirb_rsa username@jenkins.slave.bos.prod.cicd
```

In general you don't need to connect to nodes to manage, query or orchestrate them. Have a look at the <<_cicd_shell>> section to learn how to use the `cicd` command line utility.

For puppet help, go to the <<_puppet>> dedicated section.

## Customization

### system

You can add some specific configuration by editing `/etc/nixos/local-configuration.nix`.

For instance if you want to install the `geany` package, just uncomment the adhoc line.

After changing the `local-configuration.nix` file, rebuild `nixos` by using this command line:

```
→ sudo nixos-rebuild switch
```

`local-configuration.nix` is never overridden by a call for provisioning. To avoid losing your changes after a `vagrant destroy`, you might want to copy the file to `/vagrant`. In fact if `local-configuration.nix` exists on the host (where the `Vagrantfile` sits), it will be used the first time a box is provisioned.

### user

#### params

You can tweak some default settings such as "do I want to install the geppetto plugin" by modifying the `user/params.sh` file. In order to do so, copy the https://github.com/CIRB/devbox/blob/master/user/params.sh[file] to the host where the `Vagrantfile` sits. You can easily do this by using this command line on the box:

```
→ cp /tmp/user/devbox-x.x.x/user/params.sh /vagrant/params.sh
```

`vagrant provision` will automatically configure your global `.gitconfig`, if you add your `user.name` and `user.email`:

.params.sh
```
user_name="John Doe"
user_email="jdoe@cirb.brussels"
```
WARNING: Don't separate `=` with spaces

#### dotfiles

You can add any `dotfiles` repositories including your own personal ones thanks to https://github.com/RichiH/vcsh[vcsh/myrepos].

For instance you might easily add/share some `vim`, `tmux` or `zsh` configurations.

To share simple dotfiles configuration, for instance let say you want to share a default `.zshrc` file for the devbox, you can simply add the file to the https://github.com/CIRB/devbox-dotfiles[CIRB dotfiles repositry]. The file is now part of the default CIRB dotfiles source repository and will be pushed on the devbox at the next provisioning.

If you want to share a non trivial, external or optional configuration, you can use or create a specific source repository for it and register the repository https://github.com/CIRB/vcsh_mr_template/tree/master/.config/mr/available.d[here].

If you want the configuration to be active by default, you then add a link to it in the SCM, just like https://github.com/CIRB/vcsh_mr_template/blob/master/.config/mr/config.d/dotfiles.vcsh[this one]. On the other hand, if you want it inactive by default, you would ask the interested users to make the link themselves on their box.


Eventually there is a third option. Some of your configurations are personal and there is no need for them to be shared inside the CIRB organization. You normally won't need that option but it is there for flexibility sake. 3 steps are required:

1. Fork https://github.com/CIRB/vcsh_mr_template[mr CIRB template]
2. Change the https://github.com/CIRB/vcsh_mr_template/blob/master/.config/mr/available.d/mr.vcsh#L2[mr pointer] to it.
3. Change the `mr` pointer on your local box. As an example, you might follow this command line:

```
→ vcsh mr remote set-url origin git://github.com/PierreR/vcsh_mr_template.git
```

As a note, if you want to override the CIRB dotfiles completely you can replace https://github.com/PierreR/vcsh_mr_template/commit/82708255d904beffe53b9587e8f553aa8804cc37[the pointer to the dotfiles]. In order to keep such a setting after a `vagrant destroy`, you would copy the `user/params.sh` to `/vagrant` and change the `mr_template_repo_url` value.

For more information about `vcsh`, https://github.com/RichiH/vcsh/blob/master/doc/README.md#from-zero-to-vcsh[Look here].

#### local packages

If you need a package in 'user space' (and you are not interested in sharing such configuration), you might prefer the more imperative approach:

```
→ nix-env -i geany
```

You can quickly search for packages online at https://nixos.org/nixos/packages.html[nixos.org]


## How is the box generated ?

The box is generated using packer and the source files from https://github.com/zimbatm/nixbox[here]:

```
packer.exe build nixos-x86_64.json
vagrant box add devbox-x.x-pre packer_virtualbox-iso_virtualbox.box
```
The size of the 'pre box' is ~ 300M

The box is then repackaged to a full vm:

```
git clone git@github.com:CIRB/devbox.git
cd devbox
vagrant up --no-provision
vagrant provision --provision-with system
vagrant reload
rm -rf /tmp/system # on the future packaged box
vagrant package --output devbox-x.x.x --vagrantfile Vagrantfile
```

The size of the repackaged vagrant box is ~ 2G.


[[Troubleshooting]]
## Troubleshooting

Virtualbox 5.0.x::
+
For some host OS, Vagrant does not start its network interface. You will need to manually go to menu:Machine[Configuration > Network] and ensure the box "Cable Connected" is checked.

For Windows 10 users::
+
There is currently an issue regarding the Windows 10 platform as it does not allow you to use hyper-v with other hypervisors (virtualbox vmware,...) and we cannot offer a hyper-v-compatible box due to the fact that packer does not support Hyper-v.
+
The only use of hyper-v we have detected so far is by the latest version of *Docker for Windows*.
+
In order to have both docker and the devbox working at the same time, please
+
[lowerroman]
. disable hyper-v
. use virtualbox as hypervisor
. install the docker tools based on a virtualbox machine.


## Life cycle

Tickets and issues are handled in http://jira.cirb.lan/browse/CICDPROJ-150[Jira]

The versioning scheme used is semantic: `major.minor.patch`. A major jump implies some incompatible changes likely from the `vagrantFile` and forces to:

[lowerroman]
. destroy the old box losing all current statefootnote:[the README describes several tricks to keep/store your customization] : `vagrant destroy`
. remove the old box: `vagrant box remove devbox`
. add the new one: `vagrant box add devbox http://repo.irisnet.be/boxes/devbox.box`
. initialize the new box: `vagrant init devbox && vagrant up`

Please look at the https://github.com/CIRB/devbox/blob/master/CHANGELOG.adoc[Changelog] for more information.

The devbox will be maintained continuously with at least a major release every six months to follow the OS life cycle.

ifndef::env-github[]

:leveloffset: +1

include::puppet.adoc[]

include::cicd-shell.adoc[]

include::CHANGELOG.adoc[]

:leveloffset: -1

endif::env-github[]
